local groups = {}

local function get_base_colors(colors, contrast)
  local bg = vim.o.background
  local base_colors = {
    -- options (light mode by default)
    bg0 = colors.light0,
    bg1 = colors.light1,
    bg2 = colors.light2,
    bg3 = colors.light3,
    bg4 = colors.light4,
    fg0 = colors.dark0,
    fg1 = colors.dark1,
    fg2 = colors.dark2,
    fg3 = colors.dark3,
    fg4 = colors.dark4,
    red = colors.faded_red,
    green = colors.faded_green,
    yellow = colors.faded_yellow,
    blue = colors.faded_blue,
    purple = colors.faded_purple,
    aqua = colors.faded_aqua,
    orange = colors.faded_orange,
    neutral_red = colors.neutral_red,
    neutral_green = colors.neutral_green,
    neutral_yellow = colors.neutral_yellow,
    neutral_blue = colors.neutral_blue,
    neutral_purple = colors.neutral_purple,
    neutral_aqua = colors.neutral_aqua,
  }

  local dark_colors = {
    bg0 = colors.dark0,
    bg1 = colors.dark1,
    bg2 = colors.dark2,
    bg3 = colors.dark3,
    bg4 = colors.dark4,
    fg0 = colors.light0,
    fg1 = colors.light1,
    fg2 = colors.light2,
    fg3 = colors.light3,
    fg4 = colors.light4,
    red = colors.bright_red,
    green = colors.bright_green,
    yellow = colors.bright_yellow,
    blue = colors.bright_blue,
    purple = colors.bright_purple,
    aqua = colors.bright_aqua,
    orange = colors.bright_orange,
    neutral_red = colors.neutral_red,
    neutral_green = colors.neutral_green,
    neutral_yellow = colors.neutral_yellow,
    neutral_blue = colors.neutral_blue,
    neutral_purple = colors.neutral_purple,
    neutral_aqua = colors.neutral_aqua,
  }

  -- swap colors if light mode
  if bg == "light" then
    base_colors = light_colors
  end

  if contrast == "hard" then
    base_colors.bg0 = colors[bg .. "0_hard"]
  elseif contrast == "soft" then
    base_colors.bg0 = colors[bg .. "0_soft"]
  end

  base_colors.gray = colors.gray

  return base_colors
end

-- neovim terminal mode colors
local function set_terminal_colors(colors)
  vim.g.terminal_color_0 = colors.bg0
  vim.g.terminal_color_8 = colors.gray
  vim.g.terminal_color_1 = colors.neutral_red
  vim.g.terminal_color_9 = colors.red
  vim.g.terminal_color_2 = colors.neutral_green
  vim.g.terminal_color_10 = colors.green
  vim.g.terminal_color_3 = colors.neutral_yellow
  vim.g.terminal_color_11 = colors.yellow
  vim.g.terminal_color_4 = colors.neutral_blue
  vim.g.terminal_color_12 = colors.blue
  vim.g.terminal_color_5 = colors.neutral_purple
  vim.g.terminal_color_13 = colors.purple
  vim.g.terminal_color_6 = colors.neutral_aqua
  vim.g.terminal_color_14 = colors.aqua
  vim.g.terminal_color_7 = colors.fg4
  vim.g.terminal_color_15 = colors.fg1
end

groups.setup = function()
  local config = require("theme/whiteblue").config
  local palette = require("theme/whiteblue.palette")
  local colors = get_base_colors(palette, config.contrast)

  set_terminal_colors(colors)

  local groups = {
    -- Base groups
    WhiteblueFg0 = { fg = colors.fg0 },
    WhiteblueFg1 = { fg = colors.fg1 },
    WhiteblueFg2 = { fg = colors.fg2 },
    WhiteblueFg3 = { fg = colors.fg3 },
    WhiteblueFg4 = { fg = colors.fg4 },
    WhiteblueGray = { fg = colors.gray },
    WhiteblueBg0 = { fg = colors.bg0 },
    WhiteblueBg1 = { fg = colors.bg1 },
    WhiteblueBg2 = { fg = colors.bg2 },
    WhiteblueBg3 = { fg = colors.bg3 },
    WhiteblueBg4 = { fg = colors.bg4 },
    WhiteblueRed = { fg = colors.red },
    WhiteblueRedBold = { fg = colors.red, bold = config.bold },
    WhiteblueGreen = { fg = colors.green },
    WhiteblueGreenBold = { fg = colors.green, bold = config.bold },
    WhiteblueYellow = { fg = colors.yellow },
    WhiteblueYellowBold = { fg = colors.yellow, bold = config.bold },
    WhiteblueBlue = { fg = colors.blue },
    WhiteblueBlueBold = { fg = colors.blue, bold = config.bold },
    WhitebluePurple = { fg = colors.purple },
    WhitebluePurpleBold = { fg = colors.purple, bold = config.bold },
    WhiteblueAqua = { fg = colors.aqua },
    WhiteblueAquaBold = { fg = colors.aqua, bold = config.bold },
    WhiteblueOrange = { fg = colors.orange },
    WhiteblueOrangeBold = { fg = colors.orange, bold = config.bold },
    WhiteblueRedSign = { fg = colors.red, bg = colors.bg1, reverse = config.invert_signs },
    WhiteblueGreenSign = { fg = colors.green, bg = colors.bg1, reverse = config.invert_signs },
    WhiteblueYellowSign = { fg = colors.yellow, bg = colors.bg1, reverse = config.invert_signs },
    WhiteblueBlueSign = { fg = colors.blue, bg = colors.bg1, reverse = config.invert_signs },
    WhitebluePurpleSign = { fg = colors.purple, bg = colors.bg1, reverse = config.invert_signs },
    WhiteblueAquaSign = { fg = colors.aqua, bg = colors.bg1, reverse = config.invert_signs },
    WhiteblueOrangeSign = { fg = colors.orange, bg = colors.bg1, reverse = config.invert_signs },
    WhiteblueRedUnderline = { undercurl = config.undercurl, sp = colors.red },
    WhiteblueGreenUnderline = { undercurl = config.undercurl, sp = colors.green },
    WhiteblueYellowUnderline = { undercurl = config.undercurl, sp = colors.yellow },
    WhiteblueBlueUnderline = { undercurl = config.undercurl, sp = colors.blue },
    WhitebluePurpleUnderline = { undercurl = config.undercurl, sp = colors.purple },
    WhiteblueAquaUnderline = { undercurl = config.undercurl, sp = colors.aqua },
    WhiteblueOrangeUnderline = { undercurl = config.undercurl, sp = colors.orange },
    Normal = config.transparent_mode and { fg = nil, bg = nil } or { fg = colors.fg1, bg = colors.bg0 },
    NormalNC = config.dim_inactive and { fg = colors.fg0, bg = colors.bg1 } or { link = "Normal" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { fg = colors.bg4, bg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { fg = colors.green, bg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { bg = colors.bg3, bold = config.bold },
    ColorColumn = { bg = colors.bg1 },
    Conceal = { fg = colors.blue },
    CursorLineNr = { fg = colors.yellow, bg = colors.bg1 },
    NonText = { link = "WhiteblueBg2" },
    SpecialKey = { link = "WhiteblueFg4" },
    Visual = { bg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    IncSearch = { fg = colors.orange, bg = colors.bg0, reverse = config.inverse },
    QuickFixLine = { fg = colors.bg0, bg = colors.yellow, bold = config.bold },
    Underlined = { fg = colors.blue, underline = config.underline },
    StatusLine = { fg = colors.bg2, bg = colors.fg1, reverse = config.inverse },
    StatusLineNC = { fg = colors.bg1, bg = colors.fg4, reverse = config.inverse },
    VertSplit = { fg = colors.bg3, bg = colors.bg0 },
    WildMenu = { fg = colors.blue, bg = colors.bg2, bold = config.bold },
    Directory = { link = "WhiteblueGreenBold" },
    Title = { link = "WhiteblueGreenBold" },
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = config.bold },
    MoreMsg = { link = "WhiteblueYellowBold" },
    ModeMsg = { link = "WhiteblueYellowBold" },
    Question = { link = "WhiteblueOrangeBold" },
    WarningMsg = { link = "WhiteblueRedBold" },
    LineNr = { fg = colors.bg4 },
    SignColumn = { bg = colors.bg1 },
    Folded = { fg = colors.gray, bg = colors.bg1, italic = config.italic },
    FoldColumn = { fg = colors.gray, bg = colors.bg1 },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { link = "WhiteblueOrange" },
    Comment = { fg = colors.gray, italic = config.italic },
    Todo = { fg = colors.fg0, bold = config.bold, italic = config.italic },
    Error = { fg = colors.red, bold = config.bold, reverse = config.inverse },
    Statement = { link = "WhiteblueRed" },
    Conditional = { link = "WhiteblueRed" },
    Repeat = { link = "WhiteblueRed" },
    Label = { link = "WhiteblueRed" },
    Exception = { link = "WhiteblueRed" },
    Operator = { fg = colors.orange, italic = config.italic },
    Keyword = { link = "WhiteblueRed" },
    Identifier = { link = "WhiteblueBlue" },
    Function = { link = "WhiteblueGreenBold" },
    PreProc = { link = "WhiteblueAqua" },
    Include = { link = "WhiteblueAqua" },
    Define = { link = "WhiteblueAqua" },
    Macro = { link = "WhiteblueAqua" },
    PreCondit = { link = "WhiteblueAqua" },
    Constant = { link = "WhitebluePurple" },
    Character = { link = "WhitebluePurple" },
    String = { fg = colors.green, italic = config.italic },
    Boolean = { link = "WhitebluePurple" },
    Number = { link = "WhitebluePurple" },
    Float = { link = "WhitebluePurple" },
    Type = { link = "WhiteblueYellow" },
    StorageClass = { link = "WhiteblueOrange" },
    Structure = { link = "WhiteblueAqua" },
    Typedef = { link = "WhiteblueYellow" },
    Pmenu = { fg = colors.fg1, bg = colors.bg2 },
    PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = config.bold },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.bg4 },
    DiffDelete = { fg = colors.red, bg = colors.bg0, reverse = config.inverse },
    DiffAdd = { fg = colors.green, bg = colors.bg0, reverse = config.inverse },
    DiffChange = { fg = colors.aqua, bg = colors.bg0, reverse = config.inverse },
    DiffText = { fg = colors.yellow, bg = colors.bg0, reverse = config.inverse },
    SpellCap = { link = "WhiteblueBlueUnderline" },
    SpellBad = { link = "WhiteblueRedUnderline" },
    SpellLocal = { link = "WhiteblueAquaUnderline" },
    SpellRare = { link = "WhitebluePurpleUnderline" },
    -- LSP Diagnostic
    DiagnosticError = { link = "WhiteblueRed" },
    DiagnosticSignError = { link = "WhiteblueRedSign" },
    DiagnosticUnderlineError = { link = "WhiteblueRedUnderline" },
    DiagnosticWarn = { link = "WhiteblueYellow" },
    DiagnosticSignWarn = { link = "WhiteblueYellowSign" },
    DiagnosticUnderlineWarn = { link = "WhiteblueYellowUnderline" },
    DiagnosticInfo = { link = "WhiteblueBlue" },
    DiagnosticSignInfo = { link = "WhiteblueBlueSign" },
    DiagnosticUnderlineInfo = { link = "WhiteblueBlueUnderline" },
    DiagnosticHint = { link = "WhiteblueAqua" },
    DiagnosticSignHint = { link = "WhiteblueAquaSign" },
    DiagnosticUnderlineHint = { link = "WhiteblueAquaUnderline" },
    DiagnosticFloatingError = { link = "WhiteblueRed" },
    DiagnosticFloatingWarn = { link = "WhiteblueOrange" },
    DiagnosticFloatingInfo = { link = "WhiteblueBlue" },
    DiagnosticFloatingHint = { link = "WhiteblueAqua" },
    DiagnosticVirtualTextError = { link = "WhiteblueRed" },
    DiagnosticVirtualTextWarn = { link = "WhiteblueYellow" },
    DiagnosticVirtualTextInfo = { link = "WhiteblueBlue" },
    DiagnosticVirtualTextHint = { link = "WhiteblueAqua" },
    LspReferenceRead = { link = "WhiteblueYellowBold" },
    LspReferenceText = { link = "WhiteblueYellowBold" },
    LspReferenceWrite = { link = "WhiteblueOrangeBold" },
    LspCodeLens = { link = "WhiteblueGray" },
    -- nvim-treesitter
    TSStrong = { bold = config.bold },
    TSStrike = { strikethrough = config.strikethrough },
    TSEmphasis = { italic = config.italic },
    TSUnderline = { underline = config.underline },
    TSKeywordOperator = { link = "WhiteblueRed" },
    -- gitcommit
    gitcommitSelectedFile = { link = "WhiteblueGreen" },
    gitcommitDiscardedFile = { link = "WhiteblueRed" },
    -- gitsigns.nvim
    GitSignsAdd = { link = "WhiteblueGreenSign" },
    GitSignsChange = { link = "WhiteblueAquaSign" },
    GitSignsDelete = { link = "WhiteblueRedSign" },
    -- termdebug
    debugPC = { bg = palette.faded_blue },
    debugBreakpoint = { link = "WhiteblueRedSign" },
    -- vim-startify
    StartifyBracket = { link = "WhiteblueFg3" },
    StartifyFile = { link = "WhiteblueFg1" },
    StartifyNumber = { link = "WhiteblueBlue" },
    StartifyPath = { link = "WhiteblueGray" },
    StartifySlash = { link = "WhiteblueGray" },
    StartifySection = { link = "WhiteblueYellow" },
    StartifySpecial = { link = "WhiteblueBg2" },
    StartifyHeader = { link = "WhiteblueOrange" },
    StartifyFooter = { link = "WhiteblueBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    -- vim-dirvish
    DirvishPathTail = { link = "WhiteblueAqua" },
    DirvishArg = { link = "WhiteblueYellow" },
    -- netrw
    netrwDir = { link = "WhiteblueAqua" },
    netrwClassify = { link = "WhiteblueAqua" },
    netrwLink = { link = "WhiteblueGray" },
    netrwSymLink = { link = "WhiteblueFg1" },
    netrwExe = { link = "WhiteblueYellow" },
    netrwComment = { link = "WhiteblueGray" },
    netrwList = { link = "WhiteblueBlue" },
    netrwHelpCmd = { link = "WhiteblueAqua" },
    netrwCmdSep = { link = "WhiteblueFg3" },
    netrwVersion = { link = "WhiteblueGreen" },
    -- nerdtree
    NERDTreeDir = { link = "WhiteblueAqua" },
    NERDTreeDirSlash = { link = "WhiteblueAqua" },
    NERDTreeOpenable = { link = "WhiteblueOrange" },
    NERDTreeClosable = { link = "WhiteblueOrange" },
    NERDTreeFile = { link = "WhiteblueFg1" },
    NERDTreeExecFile = { link = "WhiteblueYellow" },
    NERDTreeUp = { link = "WhiteblueGray" },
    NERDTreeCWD = { link = "WhiteblueGreen" },
    NERDTreeHelp = { link = "WhiteblueFg1" },
    NERDTreeToggleOn = { link = "WhiteblueGreen" },
    NERDTreeToggleOff = { link = "WhiteblueRed" },
    -- coc.nvim
    CocErrorSign = { link = "WhiteblueRedSign" },
    CocWarningSign = { link = "WhiteblueOrangeSign" },
    CocInfoSign = { link = "WhiteblueBlueSign" },
    CocHintSign = { link = "WhiteblueAquaSign" },
    CocErrorFloat = { link = "WhiteblueRed" },
    CocWarningFloat = { link = "WhiteblueOrange" },
    CocInfoFloat = { link = "WhiteblueBlue" },
    CocHintFloat = { link = "WhiteblueAqua" },
    CocDiagnosticsError = { link = "WhiteblueRed" },
    CocDiagnosticsWarning = { link = "WhiteblueOrange" },
    CocDiagnosticsInfo = { link = "WhiteblueBlue" },
    CocDiagnosticsHint = { link = "WhiteblueAqua" },
    CocSelectedText = { link = "WhiteblueRed" },
    CocCodeLens = { link = "WhiteblueGray" },
    CocErrorHighlight = { link = "WhiteblueRedUnderline" },
    CocWarningHighlight = { link = "WhiteblueOrangeUnderline" },
    CocInfoHighlight = { link = "WhiteblueBlueUnderline" },
    CocHintHighlight = { link = "WhiteblueAquaUnderline" },
    -- telescope.nvim
    TelescopeNormal = { link = "WhiteblueFg1" },
    TelescopeSelection = { link = "WhiteblueOrangeBold" },
    TelescopeSelectionCaret = { link = "WhiteblueRed" },
    TelescopeMultiSelection = { link = "WhiteblueGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "WhiteblueBlue" },
    TelescopePromptPrefix = { link = "WhiteblueRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    -- nvim-cmp
    CmpItemAbbr = { link = "WhiteblueFg0" },
    CmpItemAbbrDeprecated = { link = "WhiteblueFg1" },
    CmpItemAbbrMatch = { link = "WhiteblueBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "WhiteblueBlueUnderline" },
    CmpItemMenu = { link = "WhiteblueGray" },
    CmpItemKindText = { link = "WhiteblueOrange" },
    CmpItemKindMethod = { link = "WhiteblueBlue" },
    CmpItemKindFunction = { link = "WhiteblueBlue" },
    CmpItemKindConstructor = { link = "WhiteblueYellow" },
    CmpItemKindField = { link = "WhiteblueBlue" },
    CmpItemKindClass = { link = "WhiteblueYellow" },
    CmpItemKindInterface = { link = "WhiteblueYellow" },
    CmpItemKindModule = { link = "WhiteblueBlue" },
    CmpItemKindProperty = { link = "WhiteblueBlue" },
    CmpItemKindValue = { link = "WhiteblueOrange" },
    CmpItemKindEnum = { link = "WhiteblueYellow" },
    CmpItemKindKeyword = { link = "WhitebluePurple" },
    CmpItemKindSnippet = { link = "WhiteblueGreen" },
    CmpItemKindFile = { link = "WhiteblueBlue" },
    CmpItemKindEnumMember = { link = "WhiteblueAqua" },
    CmpItemKindConstant = { link = "WhiteblueOrange" },
    CmpItemKindStruct = { link = "WhiteblueYellow" },
    CmpItemKindTypeParameter = { link = "WhiteblueYellow" },
    diffAdded = { link = "WhiteblueGreen" },
    diffRemoved = { link = "WhiteblueRed" },
    diffChanged = { link = "WhiteblueAqua" },
    diffFile = { link = "WhiteblueOrange" },
    diffNewFile = { link = "WhiteblueYellow" },
    diffLine = { link = "WhiteblueBlue" },
    -- html
    htmlTag = { link = "WhiteblueAquaBold" },
    htmlEndTag = { link = "WhiteblueAquaBold" },
    htmlTagName = { link = "WhiteblueBlue" },
    htmlArg = { link = "WhiteblueOrange" },
    htmlTagN = { link = "WhiteblueFg1" },
    htmlSpecialTagName = { link = "WhiteblueBlue" },
    htmlLink = { fg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "WhiteblueRed" },
    htmlBold = { fg = colors.fg0, bg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.bold, italic = config.italic },
    htmlBoldUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      bold = config.bold,
      italic = config.italic,
      underline = config.underline,
    },
    htmlUnderline = { fg = colors.fg0, bg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      fg = colors.fg0,
      bg = colors.bg0,
      italic = config.italic,
      underline = config.underline,
    },
    htmlItalic = { fg = colors.fg0, bg = colors.bg0, bold = config.italic },
    -- xml
    xmlTag = { link = "WhiteblueAquaBold" },
    xmlEndTag = { link = "WhiteblueAquaBold" },
    xmlTagName = { link = "WhiteblueBlue" },
    xmlEqual = { link = "WhiteblueBlue" },
    docbkKeyword = { link = "WhiteblueAquaBold" },
    xmlDocTypeDecl = { link = "WhiteblueGray" },
    xmlDocTypeKeyword = { link = "WhitebluePurple" },
    xmlCdataStart = { link = "WhiteblueGray" },
    xmlCdataCdata = { link = "WhitebluePurple" },
    dtdFunction = { link = "WhiteblueGray" },
    dtdTagName = { link = "WhitebluePurple" },
    xmlAttrib = { link = "WhiteblueOrange" },
    xmlProcessingDelim = { link = "WhiteblueGray" },
    dtdParamEntityPunct = { link = "WhiteblueGray" },
    dtdParamEntityDPunct = { link = "WhiteblueGray" },
    xmlAttribPunct = { link = "WhiteblueGray" },
    xmlEntity = { link = "WhiteblueRed" },
    xmlEntityPunct = { link = "WhiteblueRed" },
    -- clojure
    clojureKeyword = { link = "WhiteblueBlue" },
    clojureCond = { link = "WhiteblueOrange" },
    clojureSpecial = { link = "WhiteblueOrange" },
    clojureDefine = { link = "WhiteblueOrange" },
    clojureFunc = { link = "WhiteblueYellow" },
    clojureRepeat = { link = "WhiteblueYellow" },
    clojureCharacter = { link = "WhiteblueAqua" },
    clojureStringEscape = { link = "WhiteblueAqua" },
    clojureException = { link = "WhiteblueRed" },
    clojureRegexp = { link = "WhiteblueAqua" },
    clojureRegexpEscape = { link = "WhiteblueAqua" },
    clojureRegexpCharClass = { fg = colors.fg3, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "WhiteblueFg3" },
    clojureAnonArg = { link = "WhiteblueYellow" },
    clojureVariable = { link = "WhiteblueBlue" },
    clojureMacro = { link = "WhiteblueOrange" },
    clojureMeta = { link = "WhiteblueYellow" },
    clojureDeref = { link = "WhiteblueYellow" },
    clojureQuote = { link = "WhiteblueYellow" },
    clojureUnquote = { link = "WhiteblueYellow" },
    -- C
    cOperator = { link = "WhitebluePurple" },
    cppOperator = { link = "WhitebluePurple" },
    cStructure = { link = "WhiteblueOrange" },
    -- python
    pythonBuiltin = { link = "WhiteblueOrange" },
    pythonBuiltinObj = { link = "WhiteblueOrange" },
    pythonBuiltinFunc = { link = "WhiteblueOrange" },
    pythonFunction = { link = "WhiteblueAqua" },
    pythonDecorator = { link = "WhiteblueRed" },
    pythonInclude = { link = "WhiteblueBlue" },
    pythonImport = { link = "WhiteblueBlue" },
    pythonRun = { link = "WhiteblueBlue" },
    pythonCoding = { link = "WhiteblueBlue" },
    pythonOperator = { link = "WhiteblueRed" },
    pythonException = { link = "WhiteblueRed" },
    pythonExceptions = { link = "WhitebluePurple" },
    pythonBoolean = { link = "WhitebluePurple" },
    pythonDot = { link = "WhiteblueFg3" },
    pythonConditional = { link = "WhiteblueRed" },
    pythonRepeat = { link = "WhiteblueRed" },
    pythonDottedName = { link = "WhiteblueGreenBold" },
    -- CSS
    cssBraces = { link = "WhiteblueBlue" },
    cssFunctionName = { link = "WhiteblueYellow" },
    cssIdentifier = { link = "WhiteblueOrange" },
    cssClassName = { link = "WhiteblueGreen" },
    cssColor = { link = "WhiteblueBlue" },
    cssSelectorOp = { link = "WhiteblueBlue" },
    cssSelectorOp2 = { link = "WhiteblueBlue" },
    cssImportant = { link = "WhiteblueGreen" },
    cssVendor = { link = "WhiteblueFg1" },
    cssTextProp = { link = "WhiteblueAqua" },
    cssAnimationProp = { link = "WhiteblueAqua" },
    cssUIProp = { link = "WhiteblueYellow" },
    cssTransformProp = { link = "WhiteblueAqua" },
    cssTransitionProp = { link = "WhiteblueAqua" },
    cssPrintProp = { link = "WhiteblueAqua" },
    cssPositioningProp = { link = "WhiteblueYellow" },
    cssBoxProp = { link = "WhiteblueAqua" },
    cssFontDescriptorProp = { link = "WhiteblueAqua" },
    cssFlexibleBoxProp = { link = "WhiteblueAqua" },
    cssBorderOutlineProp = { link = "WhiteblueAqua" },
    cssBackgroundProp = { link = "WhiteblueAqua" },
    cssMarginProp = { link = "WhiteblueAqua" },
    cssListProp = { link = "WhiteblueAqua" },
    cssTableProp = { link = "WhiteblueAqua" },
    cssFontProp = { link = "WhiteblueAqua" },
    cssPaddingProp = { link = "WhiteblueAqua" },
    cssDimensionProp = { link = "WhiteblueAqua" },
    cssRenderProp = { link = "WhiteblueAqua" },
    cssColorProp = { link = "WhiteblueAqua" },
    cssGeneratedContentProp = { link = "WhiteblueAqua" },
    -- javascript
    javaScriptBraces = { link = "WhiteblueFg1" },
    javaScriptFunction = { link = "WhiteblueAqua" },
    javaScriptIdentifier = { link = "WhiteblueRed" },
    javaScriptMember = { link = "WhiteblueBlue" },
    javaScriptNumber = { link = "WhitebluePurple" },
    javaScriptNull = { link = "WhitebluePurple" },
    javaScriptParens = { link = "WhiteblueFg3" },
    -- typescript
    typescriptReserved = { link = "WhiteblueAqua" },
    typescriptLabel = { link = "WhiteblueAqua" },
    typescriptFuncKeyword = { link = "WhiteblueAqua" },
    typescriptIdentifier = { link = "WhiteblueOrange" },
    typescriptBraces = { link = "WhiteblueFg1" },
    typescriptEndColons = { link = "WhiteblueFg1" },
    typescriptDOMObjects = { link = "WhiteblueFg1" },
    typescriptAjaxMethods = { link = "WhiteblueFg1" },
    typescriptLogicSymbols = { link = "WhiteblueFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "WhiteblueFg1" },
    typescriptParens = { link = "WhiteblueFg3" },
    typescriptOpSymbols = { link = "WhiteblueFg3" },
    typescriptHtmlElemProperties = { link = "WhiteblueFg1" },
    typescriptNull = { link = "WhitebluePurple" },
    typescriptInterpolationDelimiter = { link = "WhiteblueAqua" },
    -- purescript
    purescriptModuleKeyword = { link = "WhiteblueAqua" },
    purescriptModuleName = { link = "WhiteblueFg1" },
    purescriptWhere = { link = "WhiteblueAqua" },
    purescriptDelimiter = { link = "WhiteblueFg4" },
    purescriptType = { link = "WhiteblueFg1" },
    purescriptImportKeyword = { link = "WhiteblueAqua" },
    purescriptHidingKeyword = { link = "WhiteblueAqua" },
    purescriptAsKeyword = { link = "WhiteblueAqua" },
    purescriptStructure = { link = "WhiteblueAqua" },
    purescriptOperator = { link = "WhiteblueBlue" },
    purescriptTypeVar = { link = "WhiteblueFg1" },
    purescriptConstructor = { link = "WhiteblueFg1" },
    purescriptFunction = { link = "WhiteblueFg1" },
    purescriptConditional = { link = "WhiteblueOrange" },
    purescriptBacktick = { link = "WhiteblueOrange" },
    -- coffescript
    coffeeExtendedOp = { link = "WhiteblueFg3" },
    coffeeSpecialOp = { link = "WhiteblueFg3" },
    coffeeCurly = { link = "WhiteblueOrange" },
    coffeeParen = { link = "WhiteblueFg3" },
    coffeeBracket = { link = "WhiteblueOrange" },
    -- ruby
    rubyStringDelimiter = { link = "WhiteblueGreen" },
    rubyInterpolationDelimiter = { link = "WhiteblueAqua" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    -- objc
    objcTypeModifier = { link = "WhiteblueRed" },
    objcDirective = { link = "WhiteblueBlue" },
    -- go
    goDirective = { link = "WhiteblueAqua" },
    goConstants = { link = "WhitebluePurple" },
    goDeclaration = { link = "WhiteblueRed" },
    goDeclType = { link = "WhiteblueBlue" },
    goBuiltins = { link = "WhiteblueOrange" },
    -- lua
    luaIn = { link = "WhiteblueRed" },
    luaFunction = { link = "WhiteblueAqua" },
    luaTable = { link = "WhiteblueOrange" },
    -- moonscript
    moonSpecialOp = { link = "WhiteblueFg3" },
    moonExtendedOp = { link = "WhiteblueFg3" },
    moonFunction = { link = "WhiteblueFg3" },
    moonObject = { link = "WhiteblueYellow" },
    -- java
    javaAnnotation = { link = "WhiteblueBlue" },
    javaDocTags = { link = "WhiteblueAqua" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "WhiteblueFg3" },
    javaParen1 = { link = "WhiteblueFg3" },
    javaParen2 = { link = "WhiteblueFg3" },
    javaParen3 = { link = "WhiteblueFg3" },
    javaParen4 = { link = "WhiteblueFg3" },
    javaParen5 = { link = "WhiteblueFg3" },
    javaOperator = { link = "WhiteblueOrange" },
    javaVarArg = { link = "WhiteblueGreen" },
    -- elixir
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "WhiteblueGreen" },
    elixirInterpolationDelimiter = { link = "WhiteblueAqua" },
    elixirModuleDeclaration = { link = "WhiteblueYellow" },
    -- scala
    scalaNameDefinition = { link = "WhiteblueFg1" },
    scalaCaseFollowing = { link = "WhiteblueFg1" },
    scalaCapitalWord = { link = "WhiteblueFg1" },
    scalaTypeExtension = { link = "WhiteblueFg1" },
    scalaKeyword = { link = "WhiteblueRed" },
    scalaKeywordModifier = { link = "WhiteblueRed" },
    scalaSpecial = { link = "WhiteblueAqua" },
    scalaOperator = { link = "WhiteblueFg1" },
    scalaTypeDeclaration = { link = "WhiteblueYellow" },
    scalaTypeTypePostDeclaration = { link = "WhiteblueYellow" },
    scalaInstanceDeclaration = { link = "WhiteblueFg1" },
    scalaInterpolation = { link = "WhiteblueAqua" },
    -- markdown
    markdownItalic = { fg = colors.fg3, italic = config.italic },
    markdownBold = { fg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { fg = colors.fg3, bold = config.bold, italic = config.italic },
    markdownH1 = { link = "WhiteblueGreenBold" },
    markdownH2 = { link = "WhiteblueGreenBold" },
    markdownH3 = { link = "WhiteblueYellowBold" },
    markdownH4 = { link = "WhiteblueYellowBold" },
    markdownH5 = { link = "WhiteblueYellow" },
    markdownH6 = { link = "WhiteblueYellow" },
    markdownCode = { link = "WhiteblueAqua" },
    markdownCodeBlock = { link = "WhiteblueAqua" },
    markdownCodeDelimiter = { link = "WhiteblueAqua" },
    markdownBlockquote = { link = "WhiteblueGray" },
    markdownListMarker = { link = "WhiteblueGray" },
    markdownOrderedListMarker = { link = "WhiteblueGray" },
    markdownRule = { link = "WhiteblueGray" },
    markdownHeadingRule = { link = "WhiteblueGray" },
    markdownUrlDelimiter = { link = "WhiteblueFg3" },
    markdownLinkDelimiter = { link = "WhiteblueFg3" },
    markdownLinkTextDelimiter = { link = "WhiteblueFg3" },
    markdownHeadingDelimiter = { link = "WhiteblueOrange" },
    markdownUrl = { link = "WhitebluePurple" },
    markdownUrlTitleDelimiter = { link = "WhiteblueGreen" },
    markdownLinkText = { fg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    -- haskell
    haskellType = { link = "WhiteblueBlue" },
    haskellIdentifier = { link = "WhiteblueAqua" },
    haskellSeparator = { link = "WhiteblueFg4" },
    haskellDelimiter = { link = "WhiteblueOrange" },
    haskellOperators = { link = "WhitebluePurple" },
    haskellBacktick = { link = "WhiteblueOrange" },
    haskellStatement = { link = "WhitebluePurple" },
    haskellConditional = { link = "WhitebluePurple" },
    haskellLet = { link = "WhiteblueRed" },
    haskellDefault = { link = "WhiteblueRed" },
    haskellWhere = { link = "WhiteblueRed" },
    haskellBottom = { link = "WhiteblueRedBold" },
    haskellImportKeywords = { link = "WhitebluePurpleBold" },
    haskellDeclKeyword = { link = "WhiteblueOrange" },
    haskellDecl = { link = "WhiteblueOrange" },
    haskellDeriving = { link = "WhitebluePurple" },
    haskellAssocType = { link = "WhiteblueAqua" },
    haskellNumber = { link = "WhiteblueAqua" },
    haskellPragma = { link = "WhiteblueRedBold" },
    haskellTH = { link = "WhiteblueAquaBold" },
    haskellForeignKeywords = { link = "WhiteblueGreen" },
    haskellKeyword = { link = "WhiteblueRed" },
    haskellFloat = { link = "WhiteblueAqua" },
    haskellInfix = { link = "WhitebluePurple" },
    haskellQuote = { link = "WhiteblueGreenBold" },
    haskellShebang = { link = "WhiteblueYellowBold" },
    haskellLiquid = { link = "WhitebluePurpleBold" },
    haskellQuasiQuoted = { link = "WhiteblueBlueBold" },
    haskellRecursiveDo = { link = "WhitebluePurple" },
    haskellQuotedType = { link = "WhiteblueRed" },
    haskellPreProc = { link = "WhiteblueFg4" },
    haskellTypeRoles = { link = "WhiteblueRedBold" },
    haskellTypeForall = { link = "WhiteblueRed" },
    haskellPatternKeyword = { link = "WhiteblueBlue" },
    -- json
    jsonKeyword = { link = "WhiteblueGreen" },
    jsonQuote = { link = "WhiteblueGreen" },
    jsonBraces = { link = "WhiteblueFg1" },
    jsonString = { link = "WhiteblueFg1" },
    -- mail
    mailQuoted1 = { link = "WhiteblueAqua" },
    mailQuoted2 = { link = "WhitebluePurple" },
    mailQuoted3 = { link = "WhiteblueYellow" },
    mailQuoted4 = { link = "WhiteblueGreen" },
    mailQuoted5 = { link = "WhiteblueRed" },
    mailQuoted6 = { link = "WhiteblueOrange" },
    mailSignature = { link = "Comment" },
    -- c#
    csBraces = { link = "WhiteblueFg1" },
    csEndColon = { link = "WhiteblueFg1" },
    csLogicSymbols = { link = "WhiteblueFg1" },
    csParens = { link = "WhiteblueFg3" },
    csOpSymbols = { link = "WhiteblueFg3" },
    csInterpolationDelimiter = { link = "WhiteblueFg3" },
    csInterpolationAlignDel = { link = "WhiteblueAquaBold" },
    csInterpolationFormat = { link = "WhiteblueAqua" },
    csInterpolationFormatDel = { link = "WhiteblueAquaBold" },
    -- rust btw
    rustSigil = { link = "WhiteblueOrange" },
    rustEscape = { link = "WhiteblueAqua" },
    rustStringContinuation = { link = "WhiteblueAqua" },
    rustEnum = { link = "WhiteblueAqua" },
    rustStructure = { link = "WhiteblueAqua" },
    rustModPathSep = { link = "WhiteblueFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "WhiteblueAqua" },
    -- ocaml
    ocamlOperator = { link = "WhiteblueFg1" },
    ocamlKeyChar = { link = "WhiteblueOrange" },
    ocamlArrow = { link = "WhiteblueOrange" },
    ocamlInfixOpKeyword = { link = "WhiteblueRed" },
    ocamlConstructor = { link = "WhiteblueOrange" },
    -- lspsaga.nvim
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "WhiteblueFg1" },
    LspSagaCodeActionContent = { fg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "WhiteblueFg1" },
    LspSagaAutoPreview = { link = "WhiteblueOrange" },
    TargetWord = { fg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "WhiteblueAqua" },
    LspSagaDefPreviewBorder = { link = "WhiteblueBlue" },
    LspSagaHoverBorder = { link = "WhiteblueOrange" },
    LspSagaRenameBorder = { link = "WhiteblueBlue" },
    LspSagaDiagnosticSource = { link = "WhiteblueOrange" },
    LspSagaDiagnosticBorder = { link = "WhitebluePurple" },
    LspSagaDiagnosticHeader = { link = "WhiteblueGreen" },
    LspSagaSignatureHelpBorder = { link = "WhiteblueGreen" },
    SagaShadow = { link = "WhiteblueBg0" },

    -- dashboard-nvim
    DashboardShortCut = { link = "WhiteblueOrange" },
    DashboardHeader = { link = "WhiteblueAqua" },
    DashboardCenter = { link = "WhiteblueYellow" },
    DashboardFooter = { fg = colors.purple, italic = config.italic },
  }

  for group, hl in pairs(config.overrides) do
    if groups[group] and not vim.tbl_isempty(hl) then
      groups[group].link = nil
    end
    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

return groups

